[package]
name = "rust_http_server"
version = "0.1.0"
authors = ["Sawyer Czupka <sawyerczupka@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bufstream = "0.1.4"
chrono = "0.4"
http = "0.1.17"